### ISSUE TITLE
Ask for help with the paper "Fast Graph Generation via Spectral Diffusion"

### ISSUE THREAD

**Issue by myu1999** [Ripper346/Unive-phd-thesis-template#1]
Excuse me, I'm a student at Lanzhou University in China. I noticed that you are also running the code for the paper "Fast Graph Generation via Spectral Diffusion." However, the original authors haven't provided the relevant files for QM9 and ZINC250K on GitHub. Have you managed to run it successfully?

**Comment by Ripper346** [comment]
No, and I wonder why you are raising the issue here and not in the issue I opened on their repo. I am trying with gdss code https://github.com/harryjo97/GDSS/ since most of the code they used is the same (and some things are missing from fast repo). Please, if you want to continue the discussion, quote this response in the issue on fast, not here. I am closing the issue
